# Generated by Django 5.2.8 on 2025-11-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hashed_password', models.CharField(max_length=255)),
                ('xp', models.IntegerField(default=0)),
                ('follow_count', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('token', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('country', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
