# Generated by Django 5.2.8 on 2025-11-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hashed_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
